// NOTE: This file was generated by an AI assistant to provide seed data.
package edu.stsci.proper

import grails.gorm.transactions.Transactional

import static edu.stsci.proper.Mission.HST
import static edu.stsci.proper.Mission.JWST
import static edu.stsci.proper.ProperRole.INVESTIGATOR
import static edu.stsci.proper.ProposalPhase.APPROVED

@Transactional
class BootStrap {

    def init = { servletContext ->
        Person.withTransaction {
            Person johnDoe = new Person(firstName: "John", lastName: "Doe", email: "jdoe@stsci.edu").save(flush: true, failOnError: true)
            Person janeSmith = new Person(firstName: "Jane", lastName: "Smith", email: "jsmith@jhu.edu").save(flush: true, failOnError: true)
            Person peterJones = new Person(firstName: "Peter", lastName: "Jones", email: "pjones@stsci.edu").save(flush: true, failOnError: true)
            Person maryWilliams = new Person(firstName: "Mary", lastName: "Williams", email: "mwilliams@jhu.edu").save(flush: true, failOnError: true)

            Proposal prop1 = new Proposal(mission: HST, cycle: 25, number: 12345, title: "Test Proposal 1", type: "GO", category: "Science", phase: APPROVED).save(flush: true, failOnError: true)
            Proposal prop2 = new Proposal(mission: JWST, cycle: 1, number: 67890, title: "Test Proposal 2", type: "GTO", category: "Science", phase: APPROVED).save(flush: true, failOnError: true)
            Proposal prop3 = new Proposal(mission: HST, cycle: 26, number: 11223, title: "Test Proposal 3", type: "AR", category: "Archive Research", phase: APPROVED).save(flush: true, failOnError: true)

            // Proposal 1: PI is separate from Admin PI and Contact
            new ProposalParticipant(proposal: prop1, person: johnDoe, role: INVESTIGATOR, isPrincipalInvestigator: true).save(flush: true, failOnError: true)
            new ProposalParticipant(proposal: prop1, person: janeSmith, role: INVESTIGATOR, isAdministrativePrincipalInvestigator: true, isContact: true).save(flush: true, failOnError: true)

            // Proposal 2: PI is also the Contact
            new ProposalParticipant(proposal: prop2, person: janeSmith, role: INVESTIGATOR, isPrincipalInvestigator: true, isContact: true).save(flush: true, failOnError: true)
            new ProposalParticipant(proposal: prop2, person: peterJones, role: INVESTIGATOR, isAdministrativePrincipalInvestigator: true).save(flush: true, failOnError: true)

            // Proposal 3: PI is also the Admin PI, Co-I is the Contact
            new ProposalParticipant(proposal: prop3, person: maryWilliams, role: INVESTIGATOR, isPrincipalInvestigator: true, isAdministrativePrincipalInvestigator: true).save(flush: true, failOnError: true)
            new ProposalParticipant(proposal: prop3, person: johnDoe, role: INVESTIGATOR, isContact: true).save(flush: true, failOnError: true)
        }
    }

}
